//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFChina.Course.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public string Category { get; set; }
        public string CategoryColor { get; set; }
        public string Region { get; set; }
        public string Group { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string CourseDetail { get; set; }
        public string Lecturer { get; set; }
        public string LecturerDetail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> ClassHour { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public string Class { get; set; }
        public string Sector { get; set; }
        public string Career { get; set; }
        public Nullable<bool> MainTeacher { get; set; }
    }
}
